import type {
  Activity,
  BoardDetail,
  BoardSummary,
  GanttSchedule,
  Label,
  Milestone,
  TimelineDay,
} from "./kanban-types";
import { boardMembers, currentUser } from "./users";

const labels = {
  planning: { name: "計画", className: "bg-info-soft text-info-foreground" },
  ux: { name: "UX", className: "bg-violet-soft text-violet-foreground" },
  api: { name: "API", className: "bg-success-soft text-success-foreground" },
  qa: { name: "QA", className: "bg-warning-soft text-warning-foreground" },
  release: {
    name: "公開",
    className: "bg-danger-soft text-danger-foreground",
  },
} satisfies Record<string, Label>;

export const boardSummaries: BoardSummary[] = [
  {
    name: "プロダクト計画",
    description: "ロードマップ、仕様検討、リリース準備",
    updatedAt: "今日 10:24",
    themeColor: "#0f766e",
    pinned: true,
    cardCount: 34,
    columns: ["Ideas", "Spec", "Build", "QA", "Launch"],
    members: boardMembers,
  },
  {
    name: "デザイン運用",
    description: "UI確認、文言調整、アクセシビリティ改善",
    updatedAt: "昨日 18:10",
    themeColor: "#7c3aed",
    pinned: true,
    cardCount: 27,
    columns: ["Brief", "Wire", "Review", "Handoff"],
    members: [
      { name: "藤井 美咲", initial: "藤", color: "#c2410c" },
      { name: "中村 海", initial: "中", color: "#15803d" },
      { name: "Mia Park", initial: "M", color: "#a21caf" },
      { name: "小林 遥", initial: "小", color: "#0369a1" },
    ],
  },
  {
    name: "営業パイプライン",
    description: "提案準備、商談、契約確認、導入フォロー",
    updatedAt: "6月12日",
    themeColor: "#d97706",
    isNew: true,
    cardCount: 48,
    columns: ["Lead", "Meeting", "Proposal", "Contract", "Onboard"],
    members: [
      { name: "鈴木 航", initial: "鈴", color: "#b91c1c" },
      { name: "伊藤 真央", initial: "伊", color: "#047857" },
      { name: "Ken Ito", initial: "K", color: "#6d28d9" },
      { name: "渡辺 結", initial: "渡", color: "#a16207" },
      { name: "林 直人", initial: "林", color: "#0f766e" },
      { name: "阿部 凛", initial: "阿", color: "#be185d" },
      { name: "Rui Kim", initial: "R", color: "#1d4ed8" },
      { name: "森 悠", initial: "森", color: "#92400e" },
    ],
  },
  {
    name: "採用プロセス",
    description: "候補者対応、面談調整、評価、オファー管理",
    updatedAt: "6月10日",
    themeColor: "#e11d48",
    cardCount: 30,
    columns: ["応募", "面談", "評価", "内定"],
    members: [
      { name: "石川 玲", initial: "石", color: "#2563eb" },
      { name: "吉田 杏", initial: "吉", color: "#9333ea" },
      { name: "Chris Wong", initial: "C", color: "#0891b2" },
      { name: "長谷川 透", initial: "長", color: "#dc2626" },
      { name: "原 里奈", initial: "原", color: "#4d7c0f" },
    ],
  },
];

export const productBoard: BoardDetail = {
  name: "プロダクト計画",
  description: "ロードマップ、仕様検討、リリース準備",
  updatedAt: "今日 10:24",
  themeColor: "#0f766e",
  members: boardMembers,
  columns: [
    {
      id: "ideas",
      title: "Ideas",
      accent: "#0e7490",
      cards: [
        {
          id: "SK-104",
          title: "ユーザー招待フローの整理",
          summary: "初回招待から権限付与までの分岐を1枚の導線にまとめる",
          assignees: [boardMembers[1], boardMembers[0]],
          dueDate: "6月18日",
          priority: "高",
          labels: [labels.planning, labels.ux],
          comments: 5,
        },
        {
          id: "SK-118",
          title: "カード詳細ドロワーの情報設計",
          summary: "コメント、添付、履歴を右側で扱える構成を検討する",
          assignees: [boardMembers[3], boardMembers[1]],
          dueDate: "6月20日",
          priority: "中",
          labels: [labels.ux],
          comments: 2,
        },
      ],
    },
    {
      id: "spec",
      title: "Spec",
      accent: "#7c3aed",
      cards: [
        {
          id: "SK-121",
          title: "権限ロールごとのボード操作定義",
          summary: "編集、削除、カード移動、閲覧のみの境界を仕様化する",
          assignees: [boardMembers[2], boardMembers[5], boardMembers[0]],
          dueDate: "6月19日",
          priority: "高",
          labels: [labels.planning, labels.api],
          comments: 8,
        },
        {
          id: "SK-126",
          title: "ガント表示で使う日付項目の整理",
          summary: "開始日、期限日、依存関係の有無をカード単位で確認する",
          assignees: [boardMembers[4]],
          dueDate: "6月21日",
          priority: "中",
          labels: [labels.planning],
          comments: 4,
        },
      ],
    },
    {
      id: "build",
      title: "Build",
      accent: "#0f766e",
      cards: [
        {
          id: "SK-131",
          title: "ボード一覧から詳細への遷移",
          summary: "カード全体リンクと共通ヘッダーのレイアウトを確認する",
          assignees: [boardMembers[0], boardMembers[3]],
          dueDate: "今日",
          priority: "低",
          labels: [labels.api],
          comments: 3,
        },
        {
          id: "SK-137",
          title: "列ヘッダー操作のビジュアル設計",
          summary: "ドラッグ、編集、削除、追加の優先順位が見える状態にする",
          assignees: [boardMembers[5], boardMembers[1], boardMembers[2]],
          dueDate: "6月22日",
          priority: "中",
          labels: [labels.ux],
          comments: 6,
        },
        {
          id: "SK-142",
          title: "カード追加ボタンの配置比較",
          summary: "全体追加と列内追加の両方が自然に見える密度で検証する",
          assignees: [boardMembers[1], boardMembers[4]],
          dueDate: "6月23日",
          priority: "低",
          labels: [labels.ux, labels.qa],
          comments: 1,
        },
      ],
    },
    {
      id: "qa",
      title: "QA",
      accent: "#d97706",
      cards: [
        {
          id: "SK-149",
          title: "レスポンシブ時の横スクロール確認",
          summary: "モバイル幅でも列幅と操作ボタンが潰れないことを確認する",
          assignees: [
            boardMembers[4],
            boardMembers[0],
            boardMembers[2],
            boardMembers[5],
          ],
          dueDate: "6月24日",
          priority: "高",
          labels: [labels.qa],
          comments: 7,
        },
        {
          id: "SK-153",
          title: "削除操作の確認モーダル文言",
          summary: "危険操作は通常導線から一段奥に置く設計を反映する",
          assignees: [
            boardMembers[2],
            boardMembers[4],
            boardMembers[3],
            boardMembers[1],
            boardMembers[0],
          ],
          dueDate: "6月25日",
          priority: "中",
          labels: [labels.qa, labels.release],
          comments: 3,
        },
      ],
    },
    {
      id: "launch",
      title: "Launch",
      accent: "#e11d48",
      cards: [
        {
          id: "SK-160",
          title: "公開前チェックリストの最終確認",
          summary: "メタ情報、静的出力、導線確認のチェック項目を揃える",
          assignees: [boardMembers[3], boardMembers[0], boardMembers[5]],
          dueDate: "6月27日",
          priority: "高",
          labels: [labels.release],
          comments: 9,
        },
      ],
    },
  ],
};

export const timelineDays: TimelineDay[] = [
  { date: "6/14", weekday: "日", isWeekend: true },
  { date: "6/15", weekday: "月" },
  { date: "6/16", weekday: "火" },
  { date: "6/17", weekday: "水" },
  { date: "6/18", weekday: "木" },
  { date: "6/19", weekday: "金" },
  { date: "6/20", weekday: "土", isWeekend: true },
  { date: "6/21", weekday: "日", isWeekend: true },
  { date: "6/22", weekday: "月" },
  { date: "6/23", weekday: "火" },
  { date: "6/24", weekday: "水" },
  { date: "6/25", weekday: "木" },
  { date: "6/26", weekday: "金" },
  { date: "6/27", weekday: "土", isWeekend: true },
  { date: "6/28", weekday: "日", isWeekend: true },
  { date: "6/29", weekday: "月" },
  { date: "6/30", weekday: "火" },
];

export const todayColumn = 11;

export const ganttSchedules = [
  {
    cardId: "SK-104",
    startDate: "6月16日",
    endDate: "6月18日",
    startColumn: 3,
    endColumn: 5,
  },
  {
    cardId: "SK-121",
    startDate: "6月17日",
    endDate: "6月19日",
    startColumn: 4,
    endColumn: 6,
  },
  {
    cardId: "SK-118",
    startDate: "6月18日",
    endDate: "6月20日",
    startColumn: 5,
    endColumn: 7,
  },
  {
    cardId: "SK-126",
    startDate: "6月19日",
    endDate: "6月21日",
    startColumn: 6,
    endColumn: 8,
  },
  {
    cardId: "SK-137",
    startDate: "6月20日",
    endDate: "6月22日",
    startColumn: 7,
    endColumn: 9,
  },
  {
    cardId: "SK-131",
    startDate: "6月21日",
    endDate: "6月24日",
    startColumn: 8,
    endColumn: 11,
  },
  {
    cardId: "SK-142",
    startDate: "6月22日",
    endDate: "6月23日",
    startColumn: 9,
    endColumn: 10,
  },
  {
    cardId: "SK-149",
    startDate: "6月23日",
    endDate: "6月24日",
    startColumn: 10,
    endColumn: 11,
  },
  {
    cardId: "SK-153",
    startDate: "6月24日",
    endDate: "6月25日",
    startColumn: 11,
    endColumn: 12,
  },
  {
    cardId: "SK-160",
    startDate: "6月25日",
    endDate: "6月27日",
    startColumn: 12,
    endColumn: 14,
  },
] satisfies GanttSchedule[];

export const milestones = [
  { date: "6月18日", label: "仕様レビュー", shortLabel: "レビュー", column: 5 },
  { date: "6月24日", label: "QA完了", shortLabel: "QA", column: 11 },
  { date: "6月27日", label: "公開判定", shortLabel: "公開", column: 14 },
] satisfies Milestone[];

export const activities = [
  {
    user: currentUser.name,
    action: "カードを Build に移動",
    dateLabel: "今日",
    time: "10:24",
  },
  {
    user: "高橋 葵",
    action: "カードに期限を設定",
    dateLabel: "今日",
    time: "09:52",
  },
  {
    user: "Lee Chen",
    action: "カードに添付を追加",
    dateLabel: "昨日",
    time: "17:36",
  },
  {
    user: "佐藤 花",
    action: "カードにコメントを追加",
    dateLabel: "6月22日",
    time: "16:10",
  },
] satisfies Activity[];
